# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update ICS Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update ICS file
      run: |
        python ICSVersion/GenICS.py --tg_bot_token=${{ secrets.TG_BOT_TOKEN }} --tg_chat_id=${{ secrets.TG_CHAT_ID }} 
        
    - name: Run safe dir
      run: |
          git config --global --add safe.directory /github/workspace
    
    - name: Push ICS file
      uses: actions-js/push@master
      with:
          github_token: ${{ secrets.G_T }}
          branch: main
          message: 'chore: auto update ics files'
          force: true
